use_default_settings: true

general:
  instance_name: "VANESSA SearXNG"

search:
  safe_search: 1
  formats:
    - html
    - json

server:
  secret_key: "%(ENV_SEARXNG_SECRET)s"
  bind_address: "0.0.0.0"
  limiter: false
  public_instance: false
  image_proxy: false
