from __future__ import annotations

from vanessa_shared.stream_telemetry import (
    STREAM_DURATION_MEANING_RESPONSE_HEADERS,
    STREAM_PHASE_FIRST_TOKEN_DELIVERY,
    STREAM_PHASE_RESPONSE_HEADERS,
    STREAM_STATUS_LABEL_OPENING,
    STREAM_STATUS_LABEL_RECEIVED_FIRST_TOKEN,
    STREAM_STATUS_LABEL_SETUP_COMPLETE,
    STREAM_STATUS_LABEL_STREAMED,
    STREAM_STATUS_LABEL_STREAMING,
    STREAM_STATUS_LABEL_WAITING_FIRST_TOKEN,
    TRANSPORT_DETAIL_KEYS,
    runtime_llm_binding_telemetry,
)
