from __future__ import annotations

SERVICE_VERSION = "0.1.0"
DEFAULT_PORT = 8094
DEFAULT_TEXT_TO_IMAGE_MODEL_ID = "segmind/tiny-sd"

TASK_TEXT_TO_IMAGE = "text_to_image"
TASK_LICENSE_PLATE_LOGO_REPLACEMENT = "license_plate_logo_replacement"
VALID_TASKS = {TASK_TEXT_TO_IMAGE, TASK_LICENSE_PLATE_LOGO_REPLACEMENT}

TASK_KEY_TEXT_TO_IMAGE = "image_text_to_image"
TASK_KEY_PLATE_LOGO_PROCESSOR = "image_plate_logo_replacement"

ROLE_GATEWAY = "gateway"
ROLE_TEXT_TO_IMAGE = "text_to_image"
ROLE_PLATE_LOGO = "plate_logo"
VALID_ROLES = {ROLE_GATEWAY, ROLE_TEXT_TO_IMAGE, ROLE_PLATE_LOGO}
WORKER_ROLES = (ROLE_TEXT_TO_IMAGE, ROLE_PLATE_LOGO)
DEFAULT_IMAGE_GENERATION_WORKERS = ",".join(WORKER_ROLES)

ROLE_TASKS = {
    ROLE_TEXT_TO_IMAGE: {TASK_TEXT_TO_IMAGE},
    ROLE_PLATE_LOGO: {TASK_LICENSE_PLATE_LOGO_REPLACEMENT},
}
TASK_ROLE = {
    TASK_TEXT_TO_IMAGE: ROLE_TEXT_TO_IMAGE,
    TASK_LICENSE_PLATE_LOGO_REPLACEMENT: ROLE_PLATE_LOGO,
}
