import type { ControlCardDefinition } from "./types";

export const controlCardDefinitions: ControlCardDefinition[] = [
  {
    id: "models",
    section: "aiOperations",
    titleKey: "control.items.models.title",
    descriptionKey: "control.items.models.description",
    to: "/control/models",
    icon: "models",
    minimumRole: "user",
  },
  {
    id: "quotes",
    section: "vanessaPlatform",
    titleKey: "control.items.quotes.title",
    descriptionKey: "control.items.quotes.description",
    to: "/control/quotes",
    icon: "approvals",
    minimumRole: "admin",
  },
  {
    id: "context",
    section: "aiOperations",
    titleKey: "control.items.context.title",
    descriptionKey: "control.items.context.description",
    to: "/control/context",
    icon: "models",
    minimumRole: "admin",
  },
  {
    id: "approvals",
    section: "vanessaPlatform",
    titleKey: "control.items.approvals.title",
    descriptionKey: "control.items.approvals.description",
    to: "/control/approvals",
    icon: "approvals",
    minimumRole: "admin",
  },
  {
    id: "system-health",
    section: "vanessaPlatform",
    titleKey: "control.items.systemHealth.title",
    descriptionKey: "control.items.systemHealth.description",
    to: "/control/system-health",
    icon: "health",
    minimumRole: "superadmin",
  },
  {
    id: "platform",
    section: "aiOperations",
    titleKey: "control.items.platform.title",
    descriptionKey: "control.items.platform.description",
    to: "/control/platform",
    icon: "settings",
    minimumRole: "superadmin",
  },
  {
    id: "catalog",
    section: "aiOperations",
    titleKey: "control.items.catalog.title",
    descriptionKey: "control.items.catalog.description",
    to: "/control/catalog",
    icon: "models",
    minimumRole: "superadmin",
  },
];
